name: gdb-static-pipeline

on:
  pull_request:
    branches:
      - '*'
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get install -y wget

    - name: Build
      run: make build -j$((`nproc`+1))

    - name: Pack
      run: make pack

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gdb-static
        path: build/artifacts/gdb-static*.tar.gz

    - name: Publish release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v2
      with:
        files: build/artifacts/gdb-static*.tar.gz
