name: gdb-static-release-pipeline

on:
  push:
    tags:
      - 'v*'

# Use a non-parallel single job pipeline because artifacts weigh too much. Instead,
# simply build the files in the same job they are released.
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get install -y wget

    - name: Build
      run: make build -j$((`nproc`+1))

    - name: Pack
      run: make pack

    - name: Publish release
      uses: softprops/action-gh-release@v2
      with:
        files: build/artifacts/gdb-static*.tar.gz